on:
  push:
  workflow_dispatch:

env:
  MAJOR_MINOR_PATCH: 1.0.0

name: sample-git-tag-ci

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Version suffix
        id: version_suffix
        run: |
          if [[ ${{ github.ref }} == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            echo 'for default branch pipeline'
            USE=false
            SUFFIX=''
            EXTENSION=''
          else
            echo 'for feature branch pipeline'
            USE=true
            SUFFIX=${GITHUB_REF##*/}.${{github.run_number}}
            EXTENSION="-${SUFFIX}"
          fi
          echo 'use_version_suffix' $USE
          echo 'version_suffix: ' $SUFFIX
          echo "use_version_suffix=$USE" >> $GITHUB_OUTPUT
          echo "version_suffix=$SUFFIX" >> $GITHUB_OUTPUT
          echo "extension=$EXTENSION" >> $GITHUB_OUTPUT
      - name: Semantic version
        id: semantic_version
        run: |
          SEMANTIC_VERSION="${{ env.MAJOR_MINOR_PATCH }}"
          SEMANTIC_VERSION="${SEMANTIC_VERSION}${{ steps.version_suffix.outputs.extension }}"
          echo 'MAJOR_MINOR_PATCH: ' $MAJOR_MINOR_PATCH
          echo 'SEMANTIC_VERSION: ' $SEMANTIC_VERSION
          echo "semantic_version=$SEMANTIC_VERSION" >> $GITHUB_OUTPUT
          echo "major_minor_patch=$MAJOR_MINOR_PATCH" >> $GITHUB_OUTPUT
    
      - name: Delete Git Tags
        uses: KinNeko-De/cleanup-outdated-tag-action@v0.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}